# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   encoding: utf8
#   username: root
#   password:
#   host: 127.0.0.1
#   port: 3306
#   pool: 10
#   timeout: 10000
#
# development:
#   <<: *default
#   database: development_db_name
#
# test:
#   <<: *default
#   database: test_db_name
#
# production:
#   <<: *default
#   database: production_db_name

default: &default
  adapter: mysql2
  encoding: utf8
  username: root

development:
  <<: *default
  database: development_hyper_operation_db

test:
  <<: *default
  database: test_hyper_operation_db

production:
  <<: *default
  database: production_hyper_operation_db
