language: ruby
rvm:
  - ruby
services:
  - mysql
env:
  - PHANTOMJS_VERSION=2.1.1 TZ=Europe/Berlin
cache:
  directories:
    - "travis_phantomjs"
before_install:
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"
  - gem install bundler
before_script:
  - phantomjs --version
before_script:
  - cd spec/test_app
  - bundle update
  - rails db:setup
  - cd ../../
script: bundle exec rspec
gemfile:
  - gemfiles/opal_release.gemfile
  - gemfiles/opal_master.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/opal_master.gemfile
